---
apiVersion: helm.crossplane.io/v1beta1
kind: Release
metadata:
  name: grafana
  namespace: observability
spec:
  providerConfigRef:
    name: provider-helm
  forProvider:
    chart:
      name: grafana
      repository: https://grafana.github.io/helm-charts
      version: 8.10.3
    namespace: observability
    values:
      datasources:
        datasources.yaml:
          apiVersion: 1
          datasources:
            - name: Prometheus
              type: prometheus
              url: http://prometheus-server.observability.svc.cluster.local/
              uid: "ERgg9hAnMdw4Lpf9"
            - name: Loki
              type: loki
              url: http://loki-gateway.observability.svc.cluster.local/
              uid: "ew4xLMxwfh3Yq3iA"
      dashboardProviders:
        dashboardproviders.yaml:
          apiVersion: 1
          providers:
          - name: 'default'
            orgId: 1
            folder: ''
            type: file
            disableDeletion: false
            allowUiUpdates: true
            options:
              path: /var/lib/grafana/dashboards/default

      dashboardsConfigMaps:
        default: "grafana-dashboard-overview"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboard-overview
  namespace: observability
  labels:
    grafana_dashboard: "1"
data:
  kubernetes.json: |
    {
      "__inputs": [
        {
          "name": "DS_PROMETHEUS",
          "label": "Prometheus",
          "description": "",
          "type": "datasource",
          "pluginId": "prometheus",
          "pluginName": "Prometheus"
        },
        {
          "name": "DS_LOKI",
          "label": "Loki",
          "description": "",
          "type": "datasource",
          "pluginId": "loki",
          "pluginName": "Loki"
        }
      ],
      "__elements": {},
      "__requires": [
        {
          "type": "grafana",
          "id": "grafana",
          "name": "Grafana",
          "version": "11.5.2"
        },
        {
          "type": "panel",
          "id": "logs",
          "name": "Logs",
          "version": ""
        },
        {
          "type": "datasource",
          "id": "loki",
          "name": "Loki",
          "version": "1.0.0"
        },
        {
          "type": "datasource",
          "id": "prometheus",
          "name": "Prometheus",
          "version": "1.0.0"
        },
        {
          "type": "panel",
          "id": "timeseries",
          "name": "Time series",
          "version": ""
        }
      ],
      "annotations": {
        "list": [
          {
            "builtIn": 1,
            "datasource": {
              "type": "grafana",
              "uid": "-- Grafana --"
            },
            "enable": true,
            "hide": true,
            "iconColor": "rgba(0, 211, 255, 1)",
            "name": "Annotations & Alerts",
            "type": "dashboard"
          }
        ]
      },
      "editable": true,
      "fiscalYearStartMonth": 0,
      "graphTooltip": 0,
      "id": null,
      "links": [],
      "panels": [
        {
          "datasource": {
            "type": "prometheus",
            "uid": "ERgg9hAnMdw4Lpf9"
          },
          "fieldConfig": {
            "defaults": {
              "color": {
                "mode": "palette-classic"
              },
              "custom": {
                "axisBorderShow": false,
                "axisCenteredZero": false,
                "axisColorMode": "text",
                "axisLabel": "",
                "axisPlacement": "right",
                "barAlignment": 0,
                "barWidthFactor": 0.6,
                "drawStyle": "line",
                "fillOpacity": 0,
                "gradientMode": "none",
                "hideFrom": {
                  "legend": false,
                  "tooltip": false,
                  "viz": false
                },
                "insertNulls": false,
                "lineInterpolation": "smooth",
                "lineWidth": 1,
                "pointSize": 5,
                "scaleDistribution": {
                  "type": "linear"
                },
                "showPoints": "auto",
                "spanNulls": false,
                "stacking": {
                  "group": "A",
                  "mode": "none"
                },
                "thresholdsStyle": {
                  "mode": "off"
                }
              },
              "mappings": [],
              "max": 40,
              "min": -10,
              "thresholds": {
                "mode": "absolute",
                "steps": [
                  {
                    "color": "green",
                    "value": null
                  },
                  {
                    "color": "red",
                    "value": 80
                  }
                ]
              },
              "unit": "celsius"
            },
            "overrides": []
          },
          "gridPos": {
            "h": 8,
            "w": 24,
            "x": 0,
            "y": 0
          },
          "id": 2,
          "options": {
            "legend": {
              "calcs": [],
              "displayMode": "list",
              "placement": "bottom",
              "showLegend": true
            },
            "tooltip": {
              "hideZeros": false,
              "mode": "single",
              "sort": "none"
            }
          },
          "pluginVersion": "11.5.2",
          "targets": [
            {
              "datasource": {
                "type": "prometheus",
                "uid": "ERgg9hAnMdw4Lpf9"
              },
              "disableTextWrap": false,
              "editorMode": "builder",
              "expr": "weather_temperature_actual_celcius{location=\"London\"}",
              "fullMetaSearch": false,
              "includeNullMetadata": true,
              "key": "Q-14320877-41a3-4f59-8534-dedef44bb13e-0",
              "legendFormat": "London",
              "range": true,
              "refId": "A",
              "useBackend": false
            },
            {
              "datasource": {
                "type": "prometheus",
                "uid": "ERgg9hAnMdw4Lpf9"
              },
              "disableTextWrap": false,
              "editorMode": "builder",
              "expr": "weather_temperature_actual_celcius{location=\"New York\"}",
              "fullMetaSearch": false,
              "includeNullMetadata": true,
              "instant": false,
              "key": "Q-f2ce3ddf-3fe5-4769-a8d9-64b4610d168d-1",
              "legendFormat": "New York",
              "range": true,
              "refId": "B",
              "useBackend": false
            }
          ],
          "title": "Temperature (Actual)",
          "type": "timeseries"
        },
        {
          "datasource": {
            "type": "prometheus",
            "uid": "ERgg9hAnMdw4Lpf9"
          },
          "fieldConfig": {
            "defaults": {
              "color": {
                "mode": "palette-classic"
              },
              "custom": {
                "axisBorderShow": false,
                "axisCenteredZero": false,
                "axisColorMode": "text",
                "axisLabel": "",
                "axisPlacement": "right",
                "barAlignment": 0,
                "barWidthFactor": 0.6,
                "drawStyle": "line",
                "fillOpacity": 0,
                "gradientMode": "none",
                "hideFrom": {
                  "legend": false,
                  "tooltip": false,
                  "viz": false
                },
                "insertNulls": false,
                "lineInterpolation": "smooth",
                "lineWidth": 1,
                "pointSize": 5,
                "scaleDistribution": {
                  "type": "linear"
                },
                "showPoints": "auto",
                "spanNulls": false,
                "stacking": {
                  "group": "A",
                  "mode": "none"
                },
                "thresholdsStyle": {
                  "mode": "off"
                }
              },
              "mappings": [],
              "max": 100,
              "min": 0,
              "thresholds": {
                "mode": "absolute",
                "steps": [
                  {
                    "color": "green",
                    "value": null
                  },
                  {
                    "color": "red",
                    "value": 80
                  }
                ]
              },
              "unit": "humidity"
            },
            "overrides": []
          },
          "gridPos": {
            "h": 8,
            "w": 24,
            "x": 0,
            "y": 8
          },
          "id": 4,
          "options": {
            "legend": {
              "calcs": [],
              "displayMode": "list",
              "placement": "bottom",
              "showLegend": true
            },
            "tooltip": {
              "hideZeros": false,
              "mode": "single",
              "sort": "none"
            }
          },
          "pluginVersion": "11.5.2",
          "targets": [
            {
              "datasource": {
                "type": "prometheus",
                "uid": "ERgg9hAnMdw4Lpf9"
              },
              "disableTextWrap": false,
              "editorMode": "builder",
              "expr": "weather_humidity_relative_percent{location=\"London\"}",
              "fullMetaSearch": false,
              "includeNullMetadata": true,
              "instant": false,
              "legendFormat": "London",
              "range": true,
              "refId": "A",
              "useBackend": false
            },
            {
              "datasource": {
                "type": "prometheus",
                "uid": "ERgg9hAnMdw4Lpf9"
              },
              "disableTextWrap": false,
              "editorMode": "builder",
              "expr": "weather_humidity_relative_percent{location=\"New York\"}",
              "fullMetaSearch": false,
              "includeNullMetadata": true,
              "instant": false,
              "key": "Q-56b7cf41-9244-4b28-8fec-bf801be57d4c-1",
              "legendFormat": "New York",
              "range": true,
              "refId": "B",
              "useBackend": false
            }
          ],
          "title": "Humidity (Relative)",
          "type": "timeseries"
        },
        {
          "datasource": {
            "type": "prometheus",
            "uid": "ERgg9hAnMdw4Lpf9"
          },
          "fieldConfig": {
            "defaults": {
              "color": {
                "mode": "palette-classic"
              },
              "custom": {
                "axisBorderShow": false,
                "axisCenteredZero": false,
                "axisColorMode": "text",
                "axisLabel": "",
                "axisPlacement": "right",
                "barAlignment": 0,
                "barWidthFactor": 0.6,
                "drawStyle": "line",
                "fillOpacity": 0,
                "gradientMode": "none",
                "hideFrom": {
                  "legend": false,
                  "tooltip": false,
                  "viz": false
                },
                "insertNulls": false,
                "lineInterpolation": "smooth",
                "lineWidth": 1,
                "pointSize": 5,
                "scaleDistribution": {
                  "type": "linear"
                },
                "showPoints": "auto",
                "spanNulls": false,
                "stacking": {
                  "group": "A",
                  "mode": "none"
                },
                "thresholdsStyle": {
                  "mode": "off"
                }
              },
              "mappings": [],
              "max": 50,
              "min": 0,
              "thresholds": {
                "mode": "absolute",
                "steps": [
                  {
                    "color": "green",
                    "value": null
                  },
                  {
                    "color": "red",
                    "value": 80
                  }
                ]
              },
              "unit": "velocityknot"
            },
            "overrides": []
          },
          "gridPos": {
            "h": 8,
            "w": 24,
            "x": 0,
            "y": 16
          },
          "id": 3,
          "options": {
            "legend": {
              "calcs": [],
              "displayMode": "list",
              "placement": "bottom",
              "showLegend": true
            },
            "tooltip": {
              "hideZeros": false,
              "mode": "single",
              "sort": "none"
            }
          },
          "pluginVersion": "11.5.2",
          "targets": [
            {
              "datasource": {
                "type": "prometheus",
                "uid": "ERgg9hAnMdw4Lpf9"
              },
              "disableTextWrap": false,
              "editorMode": "builder",
              "expr": "weather_wind_speed_knots{location=\"London\"}",
              "fullMetaSearch": false,
              "includeNullMetadata": true,
              "instant": false,
              "legendFormat": "London",
              "range": true,
              "refId": "A",
              "useBackend": false
            },
            {
              "datasource": {
                "type": "prometheus",
                "uid": "ERgg9hAnMdw4Lpf9"
              },
              "disableTextWrap": false,
              "editorMode": "builder",
              "expr": "weather_wind_speed_knots{location=\"New York\"}",
              "fullMetaSearch": false,
              "includeNullMetadata": true,
              "instant": false,
              "key": "Q-9e7fd184-64d3-423d-9e76-498c813a03a7-1",
              "legendFormat": "New York",
              "range": true,
              "refId": "B",
              "useBackend": false
            }
          ],
          "title": "Wind Speed",
          "type": "timeseries"
        },
        {
          "datasource": {
            "type": "loki",
            "uid": "ew4xLMxwfh3Yq3iA"
          },
          "gridPos": {
            "h": 5,
            "w": 24,
            "x": 0,
            "y": 24
          },
          "id": 1,
          "options": {
            "dedupStrategy": "none",
            "enableInfiniteScrolling": false,
            "enableLogDetails": true,
            "prettifyLogMessage": false,
            "showCommonLabels": false,
            "showLabels": false,
            "showTime": false,
            "sortOrder": "Descending",
            "wrapLogMessage": false
          },
          "pluginVersion": "11.5.2",
          "targets": [
            {
              "datasource": {
                "type": "loki",
                "uid": "ew4xLMxwfh3Yq3iA"
              },
              "direction": "backward",
              "editorMode": "builder",
              "expr": "{k8s_pod_name=\"prometheus-exporter-weather\"} |= ``",
              "queryType": "range",
              "refId": "A"
            }
          ],
          "title": "Logs",
          "type": "logs"
        }
      ],
      "refresh": "15m",
      "schemaVersion": 40,
      "tags": [],
      "templating": {
        "list": []
      },
      "time": {
        "from": "now-24h",
        "to": "now"
      },
      "timepicker": {},
      "timezone": "browser",
      "title": "Weather",
      "uid": "eefqjem6pleyoa",
      "version": 7,
      "weekStart": ""
    }