{
 "title": "Weather",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "15m",
 "panels": [
  {
   "title": "Temperature (Actual)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "weather_temperature_actual_celcius{location=\"London\"}",
     "legendFormat": "London"
    },
    {
     "expr": "weather_temperature_actual_celcius{location=\"New York\"}",
     "legendFormat": "New York"
    }
   ]
  },
  {
   "title": "Humidity (Relative)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "expr": "weather_humidity_relative_percent{location=\"London\"}",
     "legendFormat": "London"
    },
    {
     "expr": "weather_humidity_relative_percent{location=\"New York\"}",
     "legendFormat": "New York"
    }
   ]
  },
  {
   "title": "Wind Speed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "velocityknot" } },
   "targets": [
    {
     "expr": "weather_wind_speed_knots{location=\"London\"}",
     "legendFormat": "London"
    },
    {
     "expr": "weather_wind_speed_knots{location=\"New York\"}",
     "legendFormat": "New York"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{k8s_container_name=\"prometheus-exporter-weather\"} |= ``"
    }
   ]
  }
 ]
}