---
apiVersion: helm.crossplane.io/v1beta1
kind: Release
metadata:
  name: grafana
  namespace: observability
spec:
  providerConfigRef:
    name: provider-helm
  forProvider:
    chart:
      name: grafana
      repository: https://grafana.github.io/helm-charts
      version: 8.10.3
    namespace: observability
    values:
      datasources:
        datasources.yaml:
          apiVersion: 1
          datasources:
            - name: Prometheus
              type: prometheus
              url: http://prometheus-server.observability.svc.cluster.local/
              uid: "ERgg9hAnMdw4Lpf9"
            - name: Loki
              type: loki
              url: http://loki-gateway.observability.svc.cluster.local/
              uid: "ew4xLMxwfh3Yq3iA"
      dashboardProviders:
        dashboardproviders.yaml:
          apiVersion: 1
          providers:
          - name: 'weather'
            orgId: 1
            folder: ''
            type: file
            disableDeletion: false
            allowUiUpdates: true
            options:
              path: /var/lib/grafana/dashboards/weather
          - name: 'speedrun'
            orgId: 1
            folder: ''
            type: file
            disableDeletion: false
            allowUiUpdates: true
            options:
              path: /var/lib/grafana/dashboards/speedrun
      dashboardsConfigMaps:
        weather: "grafana-dashboard-weather"
        speedrun: "grafana-dashboard-speedrun"
